/* Витрина продукта: первая страница сайта. Не содержит данных пользователя. */
function vLanding(){
 const causes=['Недостаточная подготовка','Ошибка в оценке сложности','Потеря ориентира','Резкая смена погоды','Переохлаждение и перегрев','Травмы и падения','Нет связи','Паника и неверные решения','Незнание первой помощи'];
 const lv=[['NOVICE','Впервые в горах','Что взять, как одеться, что нельзя, что делать при потере группы. Короткие шаги.'],['AVERAGE','Несколько походов','Сложность маршрута, вода, ориентирование, гроза, признаки переохлаждения и перегрева.'],['ADVANCED','Опытный турист','Риски маршрута, аварийные сценарии, потеря связи, автономный выход, расширенная первая помощь.'],['EXPERT','Руководитель, инструктор','Журнал происшествий, план эвакуации, отчёт для спасателей, протокол массового происшествия.']];
 const feats=[['alert','SOS за два касания','12 ситуаций: кровотечение, перелом, потеря сознания, гроза, потеря ориентации. Короткие шаги и «нельзя».'],['bolt','Stress Mode','Один экран, одно действие. Шесть вопросов, затем план и готовое сообщение спасателям.'],['download','Работает без связи','Приложение и алгоритмы хранятся на телефоне. Отчёты группы копятся и уходят, когда сеть вернётся.'],['card','Emergency Card','Имя, контакт, маршрут, время возвращения, координаты и QR. Один экран для спасателей.'],['users','Группа','Статусы, позиции для руководителя и запрос «Все на месте» с подтверждением каждого.'],['cloud','Погода и риск','Четыре уровня риска по ветру, осадкам, грозе, видимости и температуре.'],['route','Маршрут и карта','Импорт GPX, набор высоты, профиль, точки риска, запись пройденного пути.'],['cap','Обучение','Девять коротких уроков и квизы: подготовка, гроза, переохлаждение, потеря связи.']];
 const who=[['Новичок','Не знает, с чего начать'],['Обычный турист','Оценить маршрут и погоду'],['Опытный турист','Проверить, а не читать базу'],['Руководитель группы','Контроль людей и связь'],['Семья','Дети рядом, страх потеряться'],['Школьная группа','Ответственность и подсчёт']];
 const done=[['Пошаговые алгоритмы, Stress Mode, Emergency Card','Реализовано'],['Офлайн: Service Worker, установка как приложения','Реализовано в полной версии'],['GPS, запись пути, карта, импорт GPX','Реализовано в полной версии'],['Реальная погода Open-Meteo','Реализовано в полной версии'],['Онлайн-группы через сервер','Реализовано в полной версии'],['Демо-сценарий чрезвычайной ситуации','ДЕМО'],['Казахский язык, векторные офлайн-карты, push, ИИ-ассистент','План']];
 const b=(a,t,c='',d='')=>`<button class="btn ${c}" data-a="${a}" ${d}>${t}</button>`;
 return`<div class="lp">
 <header class="lp-nav"><button class="brand" data-a="scrollto" data-id="lp-top" aria-label="Наверх"><span class="logo">${LOGO}</span>Mountain Safe</button>
  <nav class="lp-links" aria-label="Разделы сайта"><button data-a="scrollto" data-id="lp-how">Как работает</button><button data-a="scrollto" data-id="lp-levels">Уровни</button><button data-a="scrollto" data-id="lp-feat">Возможности</button><button data-a="scrollto" data-id="lp-status">Что готово</button></nav>
  ${b('go','Открыть приложение','pri sm','data-v="home"')}</header>
 <section class="lp-hero" id="lp-top"><svg class="lp-contour" viewBox="0 0 600 400" aria-hidden="true" preserveAspectRatio="xMidYMid slice"><g fill="none" stroke="var(--g)" stroke-width="1.2" opacity=".2"><path d="M-20 330C90 300 140 230 230 220s170 50 260 10 110-70 130-70"/><path d="M-20 360C100 330 160 265 240 255s160 55 250 15 120-60 140-60"/><path d="M-20 300C80 270 130 195 225 185s180 45 265 5 100-70 130-70"/><path d="M-20 270C70 240 125 160 220 150s185 40 270 0 95-75 130-75"/><path d="M40 240C100 200 150 120 230 110s190 35 265-5 85-70 120-70"/><path d="M110 190C150 150 190 85 240 75s170 30 240-10"/><path d="M175 140C200 110 225 60 250 50s130 20 190-5"/></g></svg>
  <div class="lp-copy"><span class="badge g">Безопасность в горах</span>
   <h1 class="lp-h1">Когда в горах что-то пошло не так, читать статью некогда</h1>
   <p class="lp-lead">Mountain Safe заранее оценивает риски, а в чрезвычайной ситуации ведёт по шагам, работает без связи и передаёт спасателям точные данные.</p>
   <div class="row">${b('go','Открыть приложение','pri big2','data-v="home"')}${b('demostart','Смотреть демо ЧС','big2')}</div>
   <div class="tiny">Без регистрации. Данные остаются на вашем устройстве.</div></div>
  <div class="lp-phone" aria-hidden="true"><div class="lp-scr"><div class="st-calm" style="font-size:10px">СПОКОЙНО. МЫ ПОМОЖЕМ ТЕБЕ ПОШАГОВО.</div><div class="tiny" style="margin-top:14px">Шаг 3 из 12 · Подозрение на перелом</div><div class="lp-step">Не пытайтесь вправлять конечность.</div><div class="lp-btn">Сделано, дальше</div><div class="row" style="margin-top:14px"><span class="pill" style="font-size:10px;padding:5px 9px"><span class="dot crit"></span>OFFLINE</span><span class="pill" style="font-size:10px;padding:5px 9px">112</span></div></div></div></section>
 <section class="lp-sec" id="lp-prob"><h2>Что чаще всего приводит к беде</h2><p class="muted lp-p">Опасная ситуация редко возникает из ничего. Обычно это цепочка мелких упущений.</p><div class="chips lp-wrap">${causes.map(c=>`<span class="chip">${c}</span>`).join('')}</div>
  <p class="lp-p"><b>Принцип продукта:</b> предупредить опасность раньше, чем она станет чрезвычайной ситуацией. А если она всё же наступила, человек не должен ничего искать и решать в одиночку.</p></section>
 <section class="lp-sec" id="lp-how"><h2>Как работает Stress Mode</h2><div class="grid g3 lp-flow">
  <div class="card"><span class="badge g">1. Вопросы</span><h3>Шесть коротких вопросов</h3><p class="muted small">Что произошло, есть ли опасность, кто пострадал, может ли двигаться, есть ли связь, где вы.</p></div>
  <div class="card"><span class="badge g">2. План</span><h3>Один экран — одно действие</h3><p class="muted small">Шаги собираются из ваших ответов: без длинных статей, крупным шрифтом.</p></div>
  <div class="card"><span class="badge g">3. Сообщение</span><h3>Готово для спасателей</h3><p class="muted small">Что случилось, состояние, координаты, группа и контакт. SMS, «Поделиться» или голосом по 112.</p></div></div></section>
 <section class="lp-sec" id="lp-levels"><h2>Подстраивается под ваш опыт</h2><p class="muted lp-p">Уровень меняет содержание: количество шагов, глубину советов и инструменты, а не только оформление.</p><div class="grid g2">${lv.map((l,i)=>`<div class="card"><div class="row sp"><h3>${l[0]}</h3><span class="small muted">${l[1]}</span></div><p class="muted small">${l[2]}</p>${b('enterlvl','Начать с этим уровнем','sm','data-v="'+i+'"')}</div>`).join('')}</div></section>
 <section class="lp-sec" id="lp-feat"><h2>Что внутри</h2><div class="grid g2">${feats.map(f=>`<div class="lp-feat"><span class="ti">${ic(f[0])}</span><div><h3>${f[1]}</h3><p class="muted small">${f[2]}</p></div></div>`).join('')}</div></section>
 <section class="lp-sec"><h2>Для кого</h2><div class="grid g3">${who.map(w=>`<div class="card flat"><h3>${w[0]}</h3><p class="muted small">${w[1]}</p></div>`).join('')}</div></section>
 <section class="lp-sec" id="lp-status"><h2>Что готово, а что нет</h2><p class="muted lp-p">Эта страница работает как онлайн-демо. Часть возможностей требует полной версии с сервером.</p><div class="card">${done.map(d=>`<div class="emnum"><span style="flex:1">${d[0]}</span><span class="badge ${d[1].startsWith('Реал')?'g':d[1]==='ДЕМО'?'demo':''}">${d[1]}</span></div>`).join('')}</div></section>
 <section class="lp-sec"><h2>Куда расти</h2><div class="grid g2"><div class="card flat"><h3>Казахстан</h3><p class="muted small">Маршруты нацпарков и популярных троп, местные номера и протоколы.</p></div><div class="card flat"><h3>Школы и турклубы</h3><p class="muted small">Режимы для групп, отчётность руководителя, обучение.</p></div><div class="card flat"><h3>Спасательные службы</h3><p class="muted small">Приём Emergency Card и отчёта о происшествии.</p></div><div class="card flat"><h3>Международные маршруты</h3><p class="muted small">Локальные номера служб, языки, региональные карты.</p></div></div></section>
 <section class="lp-cta"><h2>Проверьте, как это ощущается в момент опасности</h2><div class="row" style="justify-content:center">${b('go','Открыть приложение','pri big2','data-v="home"')}${b('demostart','Демо ЧС','big2')}${b('go','Нажать SOS','dng big2','data-v="sos"')}</div></section>
 <footer class="lp-foot"><p>Mountain Safe помогает принять решение и не заменяет профессиональную медицинскую или спасательную помощь. Рекомендации по первой помощи краткие и общие и требуют проверки врачом или спасательной службой перед реальным применением.</p></footer></div>`}
